;; base de mangas
(setq bm '( ;; on utilise des paires pointées car un attribut n'a qu'une seule valeur
           (
            (nom . naruto)
            (genre . shonen)
            (tomes . 66)
            (theme . ninjas)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . bleach)
            (genre . shonen)
            (tomes . 61)
            (theme . shinigamis)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . one_piece)
            (genre . shonen)
            (tomes . 72)
            (theme . pirates)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . magi)
            (genre . shonen)
            (tomes . 19)
            (theme . magie)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . toriko)
            (genre . shonen)
            (tomes . 27)
            (theme . cuisine)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . vampire_knight)
            (genre . shojo)
            (tomes . 19)
            (theme . vampires)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . infinite_stratos)
            (genre . shojo)
            (tomes . 5)
            (theme . machines)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . gurren_lagann)
            (genre . shonen)
            (tomes . 10)
            (theme . machines)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . fairy_tail)
            (genre . shonen)
            (tomes . 40)
            (theme . magie)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . angel_heart)
            (genre . seinen)
            (tomes . 33)
            (theme . policier)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . beelzebub)
            (genre . shonen)
            (tomes . 24)
            (theme . demons)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . zetsuen_no_tempest)
            (genre . shonen)
            (tomes . 9)
            (theme . magie)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . hajime_no_ippo)
            (genre . shonen)
            (tomes . 105)
            (theme . boxe)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . blood_lad)
            (genre . seinen)
            (tomes . 10)
            (theme . vampires)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . rave_master)
            (genre . shonen)
            (tomes . 35)
            (theme . magie)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . yuyu_hakusho)
            (genre . shonen)
            (tomes . 19)
            (theme . demons)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . katekyoshi_hitman_reborn)
            (genre . shonen)
            (tomes . 42)
            (theme . mafia)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . maid_sama_!)
            (genre . shojo)
            (tomes . 18)
            (theme . romance)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . Berserk)
            (genre . seinen)
            (tomes . 36)
            (theme . fantasy)
            (popularite . haute)
            (anime . non)
            )
           (
            (nom . Monster)
            (genre . seinen)
            (tomes . 18)
            (theme . policier)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . GUNNM)
            (genre . seinen)
            (tomes . 9)
            (theme . cyberpunk)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . Sanctuary)
            (genre . seinen)
            (tomes . 12)
            (theme . thriller)
            (popularite . basse)
            (anime . non)
            )
           (
            (nom . Hellsing)
            (genre . seinen)
            (tomes . 10)
            (theme . fantasy)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . Arcana)
            (genre . seinen)
            (tomes . 2)
            (theme . fantasy)
            (popularite . basse)
            (anime . non)
            )
           (
            (nom . Sailor_moon)
            (genre . shojo)
            (tomes . 18)
            (theme . magie)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . Skip_beat!)
            (genre . shojo)
            (tomes . 31)
            (theme . romantique)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . nana)
            (genre . shojo)
            (tomes . 21)
            (theme . musique)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . Fruit_basket)
            (genre . shojo)
            (tomes . 23)
            (theme . fantasy)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . Mermaid_Melody)
            (genre . shojo)
            (tomes . 7)
            (theme . romance)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . Marmalade_Boy)
            (genre . shojo)
            (tomes . 8)
            (theme . comedie)
            (popularite . basse)
            (anime . oui)
            )
           (
            (nom . city_hunter)
            (genre . shonen)
            (tomes . 35)
            (theme . policier)
            (popularite . haute)
            (anime . oui)
            )
           (
            (nom . fullmetal_alchemist)
            (genre . shonen)
            (tomes . 27)
            (theme . fantasy)
            (popularite . haute)
            (anime . oui)
            )
			(
            (nom . Saint_Seiya)
            (genre . shonen)
            (tomes . 28)
            (theme . mythologie)
            (popularite . haute)
            (anime . oui)
            )
			(
            (nom . bakuman)
            (genre . shonen)
            (tomes . 20)
            (theme . drame)
            (popularite . haute)
            (anime . oui)
            )
			(
            (nom . hunter_x_hunter)
            (genre . shonen)
            (tomes . 32)
            (theme . fantasy)
            (popularite . haute)
            (anime . oui)
            )
			(
            (nom . ippo)
            (genre . shonen)
            (tomes . 104)
            (theme . boxe)
            (popularite . haute)
            (anime . oui)
            )
			(
            (nom . deadman_worderland)
            (genre . shonen)
            (tomes . 13)
            (theme . horreur)
            (popularite . basse)
            (anime . oui)
            )
			(
            (nom . vinland_saga)
            (genre . shonen)
            (tomes . 13)
            (theme . viking)
            (popularite . basse)
            (anime . non)
            )
			(
            (nom . pandora_hearth)
            (genre . shonen)
            (tomes . 20)
            (theme . thriller)
            (popularite . basse)
            (anime . non)
            )
			(
            (nom . dengeki_daisy)
            (genre . shojo)
            (tomes . 16)
            (theme . comédie)
            (popularite . basse)
            (anime . non)
            )
			(
            (nom . sawako)
            (genre . shojo)
            (tomes . 20)
            (theme . comédie)
            (popularite . basse)
            (anime . oui)
            )
			(
            (nom . shugo_chara!)
            (genre . shojo)
            (tomes . 12)
            (theme . romance)
            (popularite . basse)
            (anime . oui)
            )
			(
            (nom . vagabond)
            (genre . seinen)
            (tomes . 36)
            (theme . historique)
            (popularite . haute)
            (anime . non)
            )
			(
            (nom . blade_of_the_immortal)
            (genre . seinen)
            (tomes . 30)
            (theme . surnaturel)
            (popularite . basse)
            (anime . oui)
            )
			(
            (nom . elfen_lied)
            (genre . seinen)
            (tomes . 12)
            (theme . horreur)
            (popularite . basse)
            (anime . oui)
            )
			(
            (nom . zetman)
            (genre . seinen)
            (tomes . 18)
            (theme . action)
            (popularite . haute)
            (anime . oui)
            )
           )
      )

(setq base_champs 
      '(
        (
         (name . tomes)
         (type . integer)
         (question . "Quel nombre de tomes souhaitez-vous approximativement ?")
         )
        (
         (name . genre)
         (type . set)
         (question . "Quel genre de mangas vous intéresse ?")
         )
        (
         (name . popularite)
         (type . set)
         (question . "Quel degré de popularité souhaitez-vous (haute ou basse) ?")
         )
        (
         (name . anime)
         (type . set)
         (question . "Désirez-vous l'existence d'un animé ?")
         )
        (
         (name . theme)
         (type . set)
         (question . "Quel est le thème qui vous intéresse ?")
         )
        )
      )

;;redéfinition de assoc
(defun value_of (key liste)
  (cdr (assoc key liste)))

;;fonction qui renvoie toutes les possibilités pour un champ donné
(defun reponses_OK (base champ)
  (let (possible)
    (dolist (c base) (pushnew (value_of champ c) possible))
    possible))

;; fonction qui teste si le manga est compatible avec la réponse de l'utilisateur
(defun incompatible (reponse champ manga)
  (if (not (eq (value_of champ manga) reponse)) t nil))
       
;; fonction qui affiche les caractéristiques d'un manga
(defun print_info (manga)
  (format t "~A~%" (value_of 'nom manga))
  (dolist (info (cdr manga)) (format t " > ~A : ~A~%" (car info) (cdr info)))
  (format t "~%")
   )

(defun systeme (bm base_champs)
  (let ((liste_m bm))
    (dolist (q base_champs)
      (if (<= (length liste_m) 1) (return-from nil)
        (progn             
                (format t "~A ~%" (value_of 'question q))
          (setq rep_possible (reponses_OK liste_m (value_of 'name q)))
          (cond
           ((eq (value_of 'name q) 'tomes) (format t "(mettre '?' si pas de choix particulier)~% > ")
            (setq reponse (read)) (cond
                                   ((eq reponse '?) nil)
                                   ((>= reponse 26) ;;taille = long
                                      (dolist (m liste_m)(if (< (value_of (value_of 'name q) m) 26) (setq liste_m (remove m liste_m))))) 
                                    ;;taille = court
                                   ((< reponse 26)(dolist (m liste_m)(if (>= (value_of (value_of 'name q) m) 26) (setq liste_m (remove m liste_m)))))
                                   (t (dolist (m liste_m)(if (incompatible reponse (value_of 'name q) m) (setq liste_m (remove m liste_m)))))
            ))
           (t
                (format t "~A (mettre '?' si pas de choix particulier)~% > " rep_possible)
                (setq reponse (read))
            (cond
             ((eq reponse '?) nil)
             (t (dolist (m liste_m)(if (incompatible reponse (value_of 'name q) m) (setq liste_m (remove m liste_m)))))
             )))
          (format t "~%")
          )
        )
      )
    (format t "--------------------------------------------~%")
    (cond
     ((= (length liste_m) 0) (format t "Aucun manga ne correspond dans la base actuelle~%") (format t "--------------------------------------------~%")
)
     ((= (length liste_m) 1) (format t "Il n'y a qu'un seul manga qui correspond à vos critères ici :~%") (print_info (car liste_m)) (format t "--------------------------------------------~%")
)
     (t (format t "~D mangas correspondent à vos choix :~%" (length liste_m)) (mapcar #'print_info liste_m) (format t "--------------------------------------------~%")
)
     )
    )
  )
              
;;Lancer le SE
(systeme bm base_champs)
